version: "3.8"
services:
  htdocs:
    image: php:7.4-apache
    volumes:
      - "./src/:/var/www/html"
    ports:
      - 8080:80
      - 4433:443
  database:
    image: postgres:latest
    restart: always
    volumes:
      - "./database/:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=docker_php
      - POSTGRES_USER=docker_php
      - POSTGRES_PASSWORD=docker_php
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080